// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using X.Data;

#nullable disable

namespace X.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250531142900_AddKantinHarcamalari")]
    partial class AddKantinHarcamalari
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("X.Models.KantinDurumlari", b =>
                {
                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<int>("AylikHak")
                        .HasColumnType("int");

                    b.Property<int>("KullanilanHak")
                        .HasColumnType("int");

                    b.Property<decimal>("OdenecekTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RaporHak")
                        .HasColumnType("int");

                    b.HasKey("SchoolNo");

                    b.ToTable("KantinDurumlari");
                });

            modelBuilder.Entity("X.Models.KantinHarcamasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Urun")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KantinHarcamalari");
                });

            modelBuilder.Entity("X.Models.Student", b =>
                {
                    b.Property<int>("SchoolNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolNo"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("SchoolNo");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("X.Models.KantinDurumlari", b =>
                {
                    b.HasOne("X.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("SchoolNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
