// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using X.Data;

#nullable disable

namespace X.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250610172217_AddRaporIstekleriTable")]
    partial class AddRaporIstekleriTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AylikTutarlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ay");

                    b.Property<int>("GunSayisi")
                        .HasColumnType("int")
                        .HasColumnName("GunSayisi");

                    b.Property<decimal>("GunlukUcret")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GunlukUcret");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("SonOdemeTarihi");

                    b.Property<decimal>("ToplamUcret")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ToplamUcret")
                        .HasComputedColumnSql("[GunSayisi] * [GunlukUcret]", true);

                    b.HasKey("Id");

                    b.ToTable("AylikTutarlar", (string)null);
                });

            modelBuilder.Entity("Gecis", b =>
                {
                    b.Property<int>("OkulNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OkulNo"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tarih")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zaman")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OkulNo");

                    b.ToTable("Gecisler", (string)null);
                });

            modelBuilder.Entity("GecisNew", b =>
                {
                    b.Property<int>("OkulNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OkulNo"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Zaman")
                        .HasColumnType("time");

                    b.HasKey("OkulNo");

                    b.ToTable("GecislerNew");
                });

            modelBuilder.Entity("GunlukGelir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("GunlukGelirler");
                });

            modelBuilder.Entity("GunlukGider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("GunlukGider", (string)null);
                });

            modelBuilder.Entity("RaporIstekleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OkulNo")
                        .HasColumnType("int");

                    b.Property<string>("RaporNedeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Zaman")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RaporIstekleri");
                });

            modelBuilder.Entity("X.Models.KantinDurumlari", b =>
                {
                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<int>("AylikHak")
                        .HasColumnType("int");

                    b.Property<int>("KullanilanHak")
                        .HasColumnType("int");

                    b.Property<int>("OdenecekTutar")
                        .HasColumnType("int");

                    b.Property<int>("RaporHak")
                        .HasColumnType("int");

                    b.HasKey("SchoolNo");

                    b.ToTable("KantinDurumlari");
                });

            modelBuilder.Entity("X.Models.KantinHarcamasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Urun")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolNo");

                    b.ToTable("KantinHarcamalari");
                });

            modelBuilder.Entity("X.Models.Student", b =>
                {
                    b.Property<int>("SchoolNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolNo"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("SchoolNo");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("X.Models.KantinDurumlari", b =>
                {
                    b.HasOne("X.Models.Student", "Student")
                        .WithOne("KantinDurumlari")
                        .HasForeignKey("X.Models.KantinDurumlari", "SchoolNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("X.Models.KantinHarcamasi", b =>
                {
                    b.HasOne("X.Models.Student", "Student")
                        .WithMany("KantinHarcamalari")
                        .HasForeignKey("SchoolNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("X.Models.Student", b =>
                {
                    b.Navigation("KantinDurumlari");

                    b.Navigation("KantinHarcamalari");
                });
#pragma warning restore 612, 618
        }
    }
}
