// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using X.Data;

#nullable disable

namespace X.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250910105202_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AylikTutarlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ay");

                    b.Property<int>("GunSayisi")
                        .HasColumnType("int")
                        .HasColumnName("GunSayisi");

                    b.Property<decimal>("GunlukUcret")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GunlukUcret");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("SonOdemeTarihi");

                    b.Property<decimal>("ToplamUcret")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ToplamUcret")
                        .HasComputedColumnSql("[GunSayisi] * [GunlukUcret]", true);

                    b.HasKey("Id");

                    b.ToTable("AylikTutarlar", (string)null);
                });

            modelBuilder.Entity("Gecis", b =>
                {
                    b.Property<int>("OkulNo")
                        .HasColumnType("int");

                    b.Property<string>("Tarih")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Zaman")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sube")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OkulNo", "Tarih", "Zaman");

                    b.ToTable("Gecisler");
                });

            modelBuilder.Entity("GunlukGelir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("GunlukGelirler");
                });

            modelBuilder.Entity("GunlukGider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("GunlukGider", (string)null);
                });

            modelBuilder.Entity("OdemeAralik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Odemeler_Aralik", (string)null);
                });

            modelBuilder.Entity("OdemeEkim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Odemeler_Ekim", (string)null);
                });

            modelBuilder.Entity("OdemeEylul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Odemeler_Eylül", (string)null);
                });

            modelBuilder.Entity("OdemeKasim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Odemeler_Kasım", (string)null);
                });

            modelBuilder.Entity("OdemeMart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Odemeler_Mart", (string)null);
                });

            modelBuilder.Entity("OdemeMayis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Odemeler_Mayıs", (string)null);
                });

            modelBuilder.Entity("OdemeNisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Odemeler_Nisan", (string)null);
                });

            modelBuilder.Entity("OdemeOcak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Odemeler_Ocak", (string)null);
                });

            modelBuilder.Entity("OdemeSubat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Odemeler_Şubat", (string)null);
                });

            modelBuilder.Entity("RaporIstekleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Durum")
                        .HasColumnType("tinyint");

                    b.Property<int>("OkulNo")
                        .HasColumnType("int");

                    b.Property<string>("RaporNedeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sinif")
                        .HasColumnType("int");

                    b.Property<string>("Sube")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Zaman")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RaporIstekleri");
                });

            modelBuilder.Entity("X.Models.KantinDurumlari", b =>
                {
                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<int>("AylikHak")
                        .HasColumnType("int");

                    b.Property<int>("KullanilanHak")
                        .HasColumnType("int");

                    b.Property<int>("OdenecekTutar")
                        .HasColumnType("int");

                    b.Property<int>("RaporHak")
                        .HasColumnType("int");

                    b.HasKey("SchoolNo");

                    b.ToTable("KantinDurumlari");
                });

            modelBuilder.Entity("X.Models.KantinHarcamasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Urun")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolNo");

                    b.ToTable("KantinHarcamalari");
                });

            modelBuilder.Entity("X.Models.OdemeAralik1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AyingGercekTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GenelOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KantinHarcamasi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RaporGunSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("RaporTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Aralik_Hesapla", (string)null);
                });

            modelBuilder.Entity("X.Models.OdemeEkim1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AyingGercekTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GenelOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KantinHarcamasi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RaporGunSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("RaporTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ekim_Hesapla", (string)null);
                });

            modelBuilder.Entity("X.Models.OdemeEylul1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AyingGercekTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GenelOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KantinHarcamasi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RaporGunSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("RaporTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Eylul_Hesapla", (string)null);
                });

            modelBuilder.Entity("X.Models.OdemeKasim1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AyingGercekTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GenelOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KantinHarcamasi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RaporGunSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("RaporTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kasim_Hesapla", (string)null);
                });

            modelBuilder.Entity("X.Models.OdemeMart1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AyingGercekTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GenelOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KantinHarcamasi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RaporGunSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("RaporTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mart_Hesapla", (string)null);
                });

            modelBuilder.Entity("X.Models.OdemeMayis1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AyingGercekTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GenelOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KantinHarcamasi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RaporGunSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("RaporTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mayis_Hesapla", (string)null);
                });

            modelBuilder.Entity("X.Models.OdemeNisan1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AyingGercekTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GenelOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KantinHarcamasi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RaporGunSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("RaporTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Nisan_Hesapla", (string)null);
                });

            modelBuilder.Entity("X.Models.OdemeOcak1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AyingGercekTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GenelOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KantinHarcamasi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RaporGunSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("RaporTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ocak_Hesapla", (string)null);
                });

            modelBuilder.Entity("X.Models.OdemeSubat1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AyingGercekTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GenelOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KantinHarcamasi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RaporGunSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("RaporTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchoolNo")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subat_Hesapla", (string)null);
                });

            modelBuilder.Entity("X.Models.Student", b =>
                {
                    b.Property<int>("SchoolNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolNo"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ParentContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.HasKey("SchoolNo");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("YemekMenusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("int");

                    b.Property<string>("MenuAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenuleri", (string)null);
                });

            modelBuilder.Entity("YemekMenusuUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("MiktarGram")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("YemekMenusuUrunleri", (string)null);
                });

            modelBuilder.Entity("YemekMenusu_Agustos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Agustos");
                });

            modelBuilder.Entity("YemekMenusu_Aralik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Aralik");
                });

            modelBuilder.Entity("YemekMenusu_Ekim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Ekim");
                });

            modelBuilder.Entity("YemekMenusu_Eylul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Eylul");
                });

            modelBuilder.Entity("YemekMenusu_Haziran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Haziran");
                });

            modelBuilder.Entity("YemekMenusu_Kasim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Kasim");
                });

            modelBuilder.Entity("YemekMenusu_Mart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Mart");
                });

            modelBuilder.Entity("YemekMenusu_Mayis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Mayis");
                });

            modelBuilder.Entity("YemekMenusu_Nisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Nisan");
                });

            modelBuilder.Entity("YemekMenusu_Ocak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Ocak");
                });

            modelBuilder.Entity("YemekMenusu_Subat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Subat");
                });

            modelBuilder.Entity("YemekMenusu_Temmuz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yemek3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YemekMenusu_Temmuz");
                });

            modelBuilder.Entity("X.Models.KantinDurumlari", b =>
                {
                    b.HasOne("X.Models.Student", "Student")
                        .WithOne("KantinDurumlari")
                        .HasForeignKey("X.Models.KantinDurumlari", "SchoolNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("X.Models.KantinHarcamasi", b =>
                {
                    b.HasOne("X.Models.Student", "Student")
                        .WithMany("KantinHarcamalari")
                        .HasForeignKey("SchoolNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("YemekMenusuUrun", b =>
                {
                    b.HasOne("YemekMenusu", "Menu")
                        .WithMany("Urunler")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("X.Models.Student", b =>
                {
                    b.Navigation("KantinDurumlari");

                    b.Navigation("KantinHarcamalari");
                });

            modelBuilder.Entity("YemekMenusu", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
